//@ sourceMappingURL=chat_conf.map
// Generated by CoffeeScript 1.6.1
(function() {

  Batman.container.workerURL = "semantictasks/js/mock_chat_worker.js";

  Batman.container.websocketURL = "none";

}).call(this);
