//@ sourceMappingURL=models.map
// Generated by CoffeeScript 1.6.1

/*
#User class#
model for users of the chat, now is only used for test purposes
Class for chat users
*/


(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Chat.User = (function(_super) {

    __extends(User, _super);

    /*
    Class for chat users
    */


    function User() {
      return User.__super__.constructor.apply(this, arguments);
    }

    User.encode('id', 'name', 'status', 'password');

    User.validate('name', {
      presence: true
    });

    User.persist(Batman.SocketStorage);

    /*
      messages are stored in socket storage
    */


    User.storageKey = 'users';

    User.login = function() {
      alert("LOGIN MODEL!");
      return console.log("LOGIN MODEL!");
    };

    return User;

  })(Batman.Model);

  /*
  #model for messages#
  contains text and user fields
  */


  Chat.Message = (function(_super) {

    __extends(Message, _super);

    /*
    model for messages
    contains text and user fields
    */


    function Message() {
      return Message.__super__.constructor.apply(this, arguments);
    }

    Message.encode('id', 'text', 'user');

    /*
      id and two other fields to be stored: text and user
      when you make models do not forget about id
    */


    Message.validate('text', {
      presence: true
    });

    /*
      validate if text is present each time we create Message
    */


    Message.persist(Batman.SocketStorage);

    /*
      messages are stored in socket storage
    */


    Message.storageKey = 'messages';

    /*
      key for local (by the browser) storage
    */


    return Message;

  })(Batman.Model);

  /*
    #model for the task#
    contains owner, title and completed of the task
  */


  Chat.Task = (function(_super) {

    __extends(Task, _super);

    /*
    model for the task
    contains owner, title and completed of the task
    */


    function Task() {
      return Task.__super__.constructor.apply(this, arguments);
    }

    Task.encode('id', 'owner', 'title', 'completed');

    Task.persist(Batman.SocketStorage);

    /*
      messages are stored in socket storage
    */


    Task.validate('title', {
      presence: true
    });

    Task.storageKey = 'tasks';

    Task.classAccessor('active', function() {
      /*return all active tasks
      */
      return this.get('all').filter(function(task) {
        return !task.get('completed');
      });
    });

    Task.classAccessor('completed', function() {
      /*
        gets all tasks and than applies filter function
      */
      return this.get('all').filter(function(task) {
        return task.get('completed');
      });
    });

    Task.wrapAccessor('title', function(core) {
      return {
        set: function(key, value) {
          return core.set.call(this, key, value != null ? value.trim() : void 0);
        }
      };
    });

    return Task;

  })(Batman.Model);

  /*
  #model for search query#
  contains id and query fields
  */


  Chat.Search = (function(_super) {

    __extends(Search, _super);

    /*
    contains id and query fields
    */


    function Search() {
      return Search.__super__.constructor.apply(this, arguments);
    }

    Search.encode('id', 'query');

    /*
      id and two other fields to be stored: text and user
      when you make models do not forget about id
    */


    Search.persist(Batman.SocketStorage);

    /*
      searches are stored in socket storage
    */


    Search.storageKey = 'searches';

    return Search;

  })(Batman.Model);

  /*
  #model for frames loading#
  */


  Chat.Search = (function(_super) {

    __extends(Search, _super);

    /*
    contains id and query fields
    */


    function Search() {
      return Search.__super__.constructor.apply(this, arguments);
    }

    Search.encode('id', 'url');

    /*
      id and url to be stored
    */


    Search.persist(Batman.SocketStorage);

    /*
      searches are stored in socket storage
    */


    Search.storageKey = 'frames';

    return Search;

  })(Batman.Model);

  Chat.SearchResult = (function(_super) {

    __extends(SearchResult, _super);

    function SearchResult() {
      return SearchResult.__super__.constructor.apply(this, arguments);
    }

    return SearchResult;

  })(Batman.Model);

  /*
  #model for messages#
  contains text and user fields
  */


  Chat.Graph = (function(_super) {

    __extends(Graph, _super);

    function Graph() {
      return Graph.__super__.constructor.apply(this, arguments);
    }

    return Graph;

  })(Batman.Model);

}).call(this);
